---

# Assert control variable values

- name: Check variables
  assert:
    that:
    - ma_hostname|string|length > 0
    - ma_hostname != 'SetMe'

# Create the namespace and other basic materials

- name: Create namespace ({{ ma_namespace }})
  k8s:
    definition: "{{ lookup('template', 'namespace.yaml.j2') }}"
    wait: yes

- name: Create DockerHub image pull secret
  k8s:
    definition: "{{ lookup('template', 'secret-dh-imagepull.yaml.j2') }}"
    wait: yes
  vars:
    pull_namespace: "{{ ma_namespace }}"
    pull_secret: "{{ ma_dockerhub_pullsecret }}"
  when: ma_dockerhub_pullsecret|string|length > 0

- name: Create namespace material
  k8s:
    definition: "{{ lookup('template', '{{ item }}.yaml.j2') }}"
    wait: yes
  loop:
  - serviceaccount
  - role
  - rolebinding-ma-sa

- name: Relax {{ ma_namespace }} 'default' service account (for cert-manager)
  k8s:
    definition: "{{ lookup('template', 'rolebinding-default-sa.yaml.j2') }}"
    wait: yes

- name: Deploy Application ({{ ma_hostname }})
  k8s:
    definition: "{{ lookup('template', '{{ item }}.yaml.j2') }}"
    wait: yes
    wait_timeout: "{{ ma_pod_ready_timeout }}"
  loop:
  - configmap
  - deployment
  - service
  - ingress
